#!/usr/bin/env python3
"""匯出：把 theme 的 tokens 與 kit 的 props/states 交給工具鏈外的世界。

    python3 wfexport.py tokens <theme.yaml> [--format json|css|ts]   # 預設 json（DTCG）
    python3 wfexport.py types  <kit.yaml>   [--format ts|json] [--types-map <map.yaml>]

設計立場：
- **tokens** 輸出對齊 DTCG（designtokens.org）標準，可直接餵 Style Dictionary / Terrazzo。
  書寫層（theme.yaml）維持好寫好讀，標準只出現在輸出層。
- **types** 輸出的是「契約」而非實作：接上資料與行為是 RD 那一層的事。
- 獨立模組，不改動 wfyaml.py 的任何行為；渲染與 lint 完全不受影響。
"""
import json
import re
import sys

import wfyaml as wf


# ── props 型別（階段 2：交付 RD 的是契約，不是實作）───────────────────────
# 刻意只給描述「值長什麼樣」的型別；沒有 shape/物件/泛型，那些屬於應用層。
_PROP_TYPES = {'text', 'number', 'boolean', 'date', 'time', 'url'}
_PROP_TS = {'text': 'string', 'number': 'number', 'boolean': 'boolean',
            'date': 'string', 'time': 'string', 'url': 'string'}


def _ts_name(kit_name):
    """kebab-case 型別名 → PascalCase。"""
    return ''.join(part.capitalize() for part in str(kit_name).split('-'))


def _kit_types_ts(components):
    """kit → TS 型別宣告。props 未標型別時視為 text（string）。"""
    lines = ['// generated by wfexport.py types --format ts, do not edit',
             '// 這是契約，不是實作：接上資料與行為是 RD 那一層的事。', '']
    for name in sorted(components):
        spec = components[name]
        ptypes = spec.get('prop-types') or {}
        fields = []
        for prop in spec.get('props', []):
            declared = ptypes.get(prop, 'text')
            if isinstance(declared, list):
                ts = ' | '.join(json.dumps(v, ensure_ascii=False) for v in declared)
            else:
                ts = _PROP_TS[declared]
            fields.append(f'  {prop}: {ts};')
        states = spec.get('states') or []
        if states:
            union = ' | '.join(json.dumps(v) for v in states)
            fields.append(f'  state?: {union};')
        if 'to' not in spec.get('props', []):        # kit 自己宣告了 to 就不重複
            fields.append('  to?: string;            // 動線目標（畫面 id）')
        lines.append(f'export type {_ts_name(name)}Props = {{')
        lines += fields
        lines.append('};')
        lines.append('')
    index = ', '.join(f"'{n}': {_ts_name(n)}Props" for n in sorted(components))
    lines.append(f'export type KitProps = {{ {index} }};')
    lines.append('')
    return '\n'.join(lines)


def _kit_prop_types(map_path):
    """讀型別對照（選配的 sidecar 檔）：`元件名: {prop: 型別}`。

        # kit/prop-types.yaml
        stamp-card: { visits: number, tone: [info, warn] }

    放在 kit 之外是刻意的：wfyaml 的 kit 只認名稱 list，
    本模組不改動它的驗證與渲染。未標註者一律視為 text。
    """
    if not map_path:
        return {}
    raw = wf._read_yaml(map_path) or {}
    if not isinstance(raw, dict):
        raise ValueError('prop-types 檔頂層必須是 {元件名: {prop: 型別}}')
    for name, declared in raw.items():
        if not isinstance(declared, dict):
            raise ValueError(f'{name}：必須是 {{prop: 型別}} dict')
        for prop, ptype in declared.items():
            if isinstance(ptype, list):
                if not ptype or any(not isinstance(v, str) for v in ptype) or len(ptype) != len(set(ptype)):
                    raise ValueError(f'{name}.{prop}：enum 必須是不重複的字串 list')
            elif ptype not in _PROP_TYPES:
                raise ValueError(
                    f'{name}.{prop}：型別只接 {sorted(_PROP_TYPES)} 或 enum list（收到 {ptype!r}）')
    return raw


def _types_export(kit_path, fmt, map_path=None):
    """`types`：kit 的 props / states → 型別宣告。"""
    wf._load_kit(kit_path, explicit=True)
    for cname, declared in _kit_prop_types(map_path).items():
        if cname not in wf._KIT_COMPONENTS:
            raise ValueError(f'prop-types 指到 kit 沒有的元件 `{cname}`')
        unknown = set(declared) - set(wf._KIT_COMPONENTS[cname].get('props', []))
        if unknown:
            raise ValueError(f'{cname}：prop-types 指到不存在的 props {sorted(unknown)}')
        wf._KIT_COMPONENTS[cname]['prop-types'] = declared
    if not wf._KIT_COMPONENTS:
        raise ValueError(f'kit 沒有任何元件：{kit_path}')
    if fmt == 'ts':
        print(_kit_types_ts(wf._KIT_COMPONENTS))
        return
    out = {}
    for name, spec in wf._KIT_COMPONENTS.items():
        ptypes = spec.get('prop-types') or {}
        out[name] = {'props': {p: ptypes.get(p, 'text') for p in spec.get('props', [])},
                     'states': spec.get('states') or [],
                     'of': spec.get('of')}
    print(json.dumps(out, ensure_ascii=False, indent=2))


# ── tokens 匯出：DTCG（Design Tokens Community Group）──────────────────────
# 書寫層（theme.yaml）維持好寫好讀，語義層對齊標準，輸出層產合規 .tokens.json。
# 標準：https://www.designtokens.org/  別名語法 {family.name} 與本工具現行寫法一致。
_DTCG_WEIGHT_ALIASES = {
    'thin', 'hairline', 'extra-light', 'ultra-light', 'light', 'normal', 'regular', 'book',
    'medium', 'semi-bold', 'demi-bold', 'bold', 'extra-bold', 'ultra-bold', 'black', 'heavy',
    'extra-black', 'ultra-black'}


def _dtcg_dimension(text):
    """'14px' / '1.5rem' → {'value': 14, 'unit': 'px'}；不合則 None。"""
    m = re.fullmatch(r'\s*(-?\d+(?:\.\d+)?)(px|rem)\s*', str(text))
    if not m:
        return None
    num = float(m.group(1))
    return {'value': int(num) if num == int(num) else num, 'unit': m.group(2)}


def _dtcg_duration(text):
    """'150ms' / '1.5s' → {'value': 150, 'unit': 'ms'}；不合則 None。"""
    m = re.fullmatch(r'\s*(-?\d+(?:\.\d+)?)(ms|s)\s*', str(text))
    if not m:
        return None
    num = float(m.group(1))
    return {'value': int(num) if num == int(num) else num, 'unit': m.group(2)}


def _dtcg_token(family, name, value):
    """單一 token → (dtcg_type, dtcg_value)；無法對應標準型別時回 (None, 原因)。

    優先序：別名 → 家族語義（color/font）→ 值的形狀。
    刻意不猜：對不上就不匯出並說明原因，而不是塞一個不合規的型別。
    """
    if isinstance(value, (list, tuple)):
        nums = list(value)
        if len(nums) == 4 and all(isinstance(n, (int, float)) for n in nums):
            if not (0 <= nums[0] <= 1 and 0 <= nums[2] <= 1):
                return None, 'cubicBezier 的 x 座標必須落在 [0, 1]'
            return 'cubicBezier', [float(n) for n in nums]
        if all(isinstance(n, str) for n in nums):
            return 'fontFamily', list(nums)
        return None, '陣列只支援 cubicBezier（四個數字）或 fontFamily（字串陣列）'

    text = str(value).strip()
    if text.startswith('{') and text.endswith('}'):
        return 'alias', text                      # 型別由被參照的 token 決定（DTCG §5.2.2）

    if family == 'color':
        return 'color', text
    if family == 'font':
        if name in ('body', 'family', 'mono', 'serif', 'sans'):
            return 'fontFamily', text
        if name in ('weight', 'bold', 'regular'):
            if re.fullmatch(r'\d+', text):
                w = int(text)
                if not 1 <= w <= 1000:
                    return None, 'fontWeight 必須在 1–1000'
                return 'fontWeight', w
            if text in _DTCG_WEIGHT_ALIASES:
                return 'fontWeight', text
            return None, f'fontWeight 不接受 {text!r}（1–1000 或標準別名）'

    dim = _dtcg_dimension(text)
    if dim:
        return 'dimension', dim
    dur = _dtcg_duration(text)
    if dur:
        return 'duration', dur
    if re.fullmatch(r'-?\d+(?:\.\d+)?', text):
        num = float(text)
        return 'number', int(num) if num == int(num) else num
    if re.fullmatch(r'#[0-9A-Fa-f]{3,8}', text):
        return 'color', text

    if re.fullmatch(r'-?\d+(?:\.\d+)?(em|%|vh|vw|ch)', text):
        return None, f'DTCG dimension 只支援 px / rem（收到 {text!r}）'
    return None, f'無對應的 DTCG 型別（{text!r}）'


def _token_raw(entry):
    """取 token 原值：已是 DTCG 形狀（含 $value）就取 $value，否則原樣。"""
    if isinstance(entry, dict) and '$value' in entry:
        return entry['$value']
    return entry


def _tokens_to_dtcg(tokens):
    """theme tokens → (DTCG dict, 略過清單)。preset 不是 token，不匯出。"""
    out, skipped = {}, []
    for family, entries in (tokens or {}).items():
        if family == 'preset' or not isinstance(entries, dict):
            continue
        group, types = {}, set()
        for name, entry in entries.items():
            kind, val = _dtcg_token(family, name, _token_raw(entry))
            if kind is None:
                skipped.append((f'{family}.{name}', val))
                continue
            if kind == 'alias':
                group[str(name)] = {'$value': val}
                continue
            group[str(name)] = {'$type': kind, '$value': val}
            types.add(kind)
        if not group:
            continue
        if len(types) == 1:                       # 同型家族：$type 提到群組層（DTCG §6.3）
            only = types.pop()
            for tok in group.values():
                tok.pop('$type', None)
            out[family] = {'$type': only, **group}
        else:
            out[family] = group
    return out, skipped


def _token_css_value(value):
    """token 值 → CSS 值。陣列依形狀轉 cubic-bezier() 或字型後備串。"""
    if isinstance(value, (list, tuple)):
        nums = list(value)
        if len(nums) == 4 and all(isinstance(n, (int, float)) for n in nums):
            return 'cubic-bezier(' + ', '.join(str(n) for n in nums) + ')'
        return ', '.join(str(n) for n in nums)
    return wf._resolve_value(str(value))


def _tokens_as_css(tokens):
    """扁平的 `:root{--wf-*}`，只含 token，不含任何線框機制的規則。"""
    decls = []
    for family, entries in (tokens or {}).items():
        if family == 'preset' or not isinstance(entries, dict):
            continue
        for name, entry in entries.items():
            decls.append(f'  {wf._theme_var_name(family, name)}: {_token_css_value(_token_raw(entry))};')
    return '/* generated by wfexport.py tokens --format css, do not edit */\n:root {\n' + \
           '\n'.join(decls) + '\n}'


def _tokens_as_ts(tokens):
    """扁平化成 TS 常數（別名已解析），供正式程式碼直接引用。"""
    out = {}
    for family, entries in (tokens or {}).items():
        if family == 'preset' or not isinstance(entries, dict):
            continue
        for name, entry in entries.items():
            raw = _token_raw(entry)
            if isinstance(raw, (list, tuple)):
                out[f'{family}.{name}'] = list(raw)
            else:
                text = str(raw)
                out[f'{family}.{name}'] = wf._THEME_FLATVALS.get(f'{family}.{name}', text) \
                    if text.startswith('{') else raw
    lines = ['// generated by wfexport.py tokens --format ts, do not edit',
             'export const tokens = {']
    for path in sorted(out):
        lines.append(f'  {json.dumps(path)}: {json.dumps(out[path], ensure_ascii=False)},')
    lines += ['} as const;', '', 'export type TokenName = keyof typeof tokens;', '']
    return '\n'.join(lines)


def _tokens_export(theme_path, fmt):
    """`tokens`：把 theme 的 tokens 匯出成 DTCG JSON / CSS / TS。"""
    wf._load_theme(theme_path)                       # 沿用既有驗證（未定義 ref、循環在此炸）
    tokens = wf._THEME_TOKENS
    if fmt == 'css':
        print(_tokens_as_css(tokens))
        return
    if fmt == 'ts':
        print(_tokens_as_ts(tokens))
        return
    dtcg, skipped = _tokens_to_dtcg(tokens)
    print(json.dumps(dtcg, ensure_ascii=False, indent=2))
    for path, why in skipped:
        print(f'warning: tokens.{path} 未匯出 —— {why}', file=sys.stderr)


def _argval(flag, argv):
    if flag in argv:
        i = argv.index(flag)
        if i + 1 < len(argv):
            return argv[i + 1]
    return None


def main(argv=None):
    argv = list(sys.argv[1:] if argv is None else argv)
    if not argv or argv[0] in ('-h', '--help') or argv[0] not in ('tokens', 'types'):
        print(__doc__.strip(), file=sys.stderr)
        return 1
    cmd, rest = argv[0], argv[1:]
    tmap = _argval('--types-map', rest)
    paths = [a for a in rest if not a.startswith('-') and a != tmap]
    fmt = (_argval('--format', rest) or ('json' if cmd == 'tokens' else 'ts')).lower()
    if fmt in paths:
        paths.remove(fmt)
    if not paths:
        print(f'usage: wfexport.py {cmd} <file.yaml> [--format ...]', file=sys.stderr)
        return 1
    try:
        if cmd == 'tokens':
            if fmt not in ('json', 'css', 'ts'):
                raise ValueError(f"tokens 的 --format 只接受 json / css / ts（收到 {fmt!r}）")
            _tokens_export(paths[0], fmt)
        else:
            if fmt not in ('ts', 'json'):
                raise ValueError(f"types 的 --format 只接受 ts / json（收到 {fmt!r}）")
            _types_export(paths[0], fmt, tmap)
    except Exception as exc:                          # 作者錯誤印一行，不噴 traceback
        first, _, more = str(exc).partition('\n')
        print(f'error: {first}', file=sys.stderr)
        for line in more.splitlines():
            if line.strip():
                print(f'  {line}', file=sys.stderr)
        return 1
    return 0


if __name__ == '__main__':
    sys.exit(main())
